// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package interfaces

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockIngestionOrk creates a new instance of MockIngestionOrk. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIngestionOrk(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIngestionOrk {
	mock := &MockIngestionOrk{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIngestionOrk is an autogenerated mock type for the IngestionOrk type
type MockIngestionOrk struct {
	mock.Mock
}

type MockIngestionOrk_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIngestionOrk) EXPECT() *MockIngestionOrk_Expecter {
	return &MockIngestionOrk_Expecter{mock: &_m.Mock}
}
